"""add grounding level columns

Revision ID: 6b62e0b0b88d
Revises: b1c2d3e4f5a6
Create Date: 2026-08-27 18:46:32.680875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b62e0b0b88d'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('grounding_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='Easy'))
    op.add_column('users', sa.Column('grounding_level_assessed_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'grounding_level_assessed_date')
    op.drop_column('users', 'grounding_level')
    # ### end Alembic commands ###
